services:
  web:
    build: .
    container_name: web
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  web-debug:
    build: .
    container_name: webdev
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
      - "5678:5678"
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      - db
  db:
    image: postgres:17.1-alpine3.20
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=sysuser@mail.com
      - PGADMIN_DEFAULT_PASSWORD=syspasswd
    ports:
      - 8082:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  worker:
    build: .
    container_name: celery_worker
    command: celery -A app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
  beat:
    build: .
    container_name: celery_beat
    command: celery -A app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  pgadmin_data:
