### Variáveis globais
@url = http://localhost:8001/api/v1
@email = "john@mail.com"
@password = "password@123"
@id = {{SignUp.response.body.id}}
@token = {{SignIn.response.body.token}}


### Register a new customer
# @name SignUp
POST {{url}}/auth/register/
Content-Type: application/json

{
    "name": "John Doe",
    "email": {{email}},
    "password": {{password}},
    "password_confirm": "password@123"
}


### Make login
# @name SignIn
POST {{url}}/auth/login/
Content-Type: application/json

{
    "email": {{email}},
    "password": {{password}}
}

### Get customer by ID
GET {{url}}/customer/{{id}}

### Create order
# @name CreateOrder
POST {{url}}/orders/
Content-Type: application/json
Authorization: Token {{token}}

{
    "customer_id": 1,
    "items": [
        {
            "id": 1,
            "quantity": 2
        },
        {
            "id": 2,
            "quantity": 1
        }
    ]
}

### Get order by ID
# @name GetOrder
GET {{url}}/orders/1
Content-Type: application/json
Authorization: Token {{token}}
### Get all orders

# @name GetAllOrders
GET {{url}}/orders?customer_id=1&offset=0&limit=50
Content-Type: application/json
Authorization: Token {{token}}

### Get all products
# @name GetAllProducts
GET {{url}}/products
Content-Type: application/json
Authorization: Token {{token}}

### Get product by ID
# @name GetProduct
GET {{url}}/products/1
Content-Type: application/json
Authorization: Token {{token}}


